import { LazyMotion, domAnimation } from 'motion/react';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { ThemeProvider } from 'next-themes';
import { Roboto, Ubuntu } from 'next/font/google';
import { ReactNode } from 'react';
import { Toaster } from 'sonner';

import { ApolloClientProvider } from '@/providers';
import { cn } from '@/utils';

import './globals.css';

const ubuntu = Ubuntu({
	variable: '--font-ubuntu',
	subsets: ['latin'],
	fallback: ['system-ui', 'sans-serif'],
	weight: ['300', '400', '700'],
	style: ['normal', 'italic'],
});
const roboto = Roboto({
	variable: '--font-roboto',
	subsets: ['latin'],
	fallback: ['system-ui', 'sans-serif'],
	weight: ['300', '400', '700'],
	style: ['normal', 'italic'],
});

export const metadata: Metadata = {
	title: {
		template: 'HUMAN DRAFT | %s',
		default: 'HUMAN DRAFT',
	},
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	const locale = await getLocale();
	const messages = await getMessages();

	return (
		<html
			lang={locale}
			suppressHydrationWarning>
			<body className={cn(ubuntu.variable, roboto.variable, 'antialiased')}>
				<ApolloClientProvider>
					<NextIntlClientProvider messages={messages}>
						<ThemeProvider
							attribute='class'
							defaultTheme='light'
							themes={['light', 'dark']}
							enableSystem={false}>
							<LazyMotion
								features={domAnimation}
								strict>
								{children}
								<Toaster
									position='bottom-right'
									duration={5000}
									closeButton
								/>
							</LazyMotion>
						</ThemeProvider>
					</NextIntlClientProvider>
				</ApolloClientProvider>
			</body>
		</html>
	);
}
