query getAllUsers($searchParams: SearchParamsInput!) {
	getAllUsersPagination(searchParams: $searchParams) {
		data {
			id
			avatarUrl
			username
			description
		}
		page
		perPage
		totalCount
		totalPages
	}
}
