query getAllPosts($searchParams: SearchParamsInput!) {
	getAllPostsPagination(searchParams: $searchParams) {
		data {
			...PostFragment
			tags {
				id
				name
			}
		}
		page
		perPage
		totalCount
		totalPages
	}
}
