query getAllPosts($searchParams: SearchParamsInput!) {
	getAllPostsPagination(searchParams: $searchParams) {
		data {
			id
			title
			content
			createdAt
			updatedAt
			tags {
				id
				name
			}
			likesCount
			viewsCount
			commentsCount
			author {
				username
				avatarUrl
			}
		}
		page
		perPage
		totalCount
		totalPages
	}
}
