query getAllUsers($searchParams: SearchParamsInput!, $searchStr: String!, $onlySubscriptions: Boolean!) {
	getAllUsersPagination(searchParams: $searchParams, searchStr: $searchStr, onlySubscriptions: $onlySubscriptions) {
		data {
			id
			avatarUrl
			username
			description
		}
		page
		perPage
		totalCount
		totalPages
	}
}
