query GetAllBlogs($searchParams: SearchParamsInput!, $filters: FiltersInput) {
	getAllBlogsPagination(searchParams: $searchParams, filters: $filters) {
		data {
			...BlogFragment
		}
		page
		perPage
		totalPages
		totalCount
	}
}
