query getPostById($postId: String!) {
	getPostById(postId: $postId) {
		id
		title
		content
		createdAt
		updatedAt
		blog {
			id
		}
		author {
			username
			avatarUrl
		}
		comments {
			...CommentFields
			replies {
				...CommentFields
				replies {
					...CommentFields
					replies {
						...CommentFields
					}
				}
			}
		}
		tags {
			id
			name
		}
		likesCount
		viewsCount
		commentsCount
	}
}

fragment CommentFields on CommentModel {
	id
	text
	parentId
	createdAt
	author {
		username
		avatarUrl
	}
}
