query getPostById($postId: String!) {
	getPostById(postId: $postId) {
		id
		title
		content
		createdAt
		updatedAt
		blog {
			id
		}
		author {
			username
			avatarUrl
		}
		comments {
			id
			author {
				id
			}
		}
		tags {
			id
			name
		}
		likesCount
		viewsCount
		commentsCount
	}
}
