query GetUserByUsername($username: String!) {
	getUserByUsername(username: $username) {
		id
		username
		description
		avatarUrl
		posterUrl
		posts {
			id
			title
			content
			createdAt
			updatedAt
			tags {
				id
				name
			}
			likesCount
			viewsCount
			commentsCount
			author {
				username
				avatarUrl
			}
		}
		blogs {
			...BlogFragment
		}
	}
}
